### ISSUE TITLE
Rebuild autodiscover_templates for Python 3 and django 1.8

### ISSUE THREAD

**Issue by walterrenner** [arteria/cmsplugin-contact-plus#50]
The `autodiscover_templates` machanism is not working with Python3 and the new TEMPLATES settings in django 1.8

See also:
* #48
* #49

**Comment by philippeowagner** [comment]
There is [an internal app](https://github.com/arteria/ar-autodiscover-templates/) for that @walterrenner . We use the same mechanism in different plugins, so we should refactor the app first, open source it and than handle this issue here and refactor the other apps listen below.

* cmsplugin_carousel
* djangocms-carousel
* cmsplugin_gallery
* djangocms-gallery
* django-shop-simplevariations-sku
* app-end ?

**Comment by jvamvas** [comment]
Instead of being rebuilt, the (undocumented) autodiscovery feature has been removed altogether.
